name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 0
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_trim: yes
          config_timezone: Europe/Amsterdam
          plugin_lines: yes
          
          
          
          
